# Generated by Django 2.2.5 on 2019-12-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(default='', max_length=100)),
                ('full_name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(default='', max_length=100)),
                ('college', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='', max_length=1000)),
            ],
        ),
    ]
